spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000